configurationName: "PWGGA_configuration_data"
pass: "default"
inputObjects:
    cells:
        defaultCells:
            branchName: "usedefault"
    clusterContainers:
        defaultClusterContainer:
            branchName: "usedefault"
        ClusterContainerV1:
            branchName: "V1ClustersBranch"
        ClusterContainerS500A100:
            branchName: "S500A100ClustersBranch"
        ClusterContainerS500A125:
            branchName: "S500A125ClustersBranch"
        ClusterContainerS500A150:
            branchName: "S500A150ClustersBranch"
        ClusterContainerS500A300:
            branchName: "S500A300ClustersBranch"
        ClusterContainerS1000A300:
            branchName: "S1000A300ClustersBranch"
    trackContainers:
        defaultTrackContainer:
            branchName: "usedefault"

CellEnergy:
    createHistos: true
CellEnergy_defaultSetting:
    enabled: true
    enableNewTempCalib: true
    enableShaperCorrection: true

CellBadChannel:
    createHistos: true
    load1DBadChMap: true
    customBadChannelFilePath: "$ALICE_PHYSICS/PWGGA/GammaConv/macros/data/EMCALBadChannelspPb8TeV_1D.root"
CellBadChannel_defaultSetting:
    enabled: true

CellTimeCalib:
    createHistos: true
CellTimeCalib_defaultSetting:
    enabled: true

Clusterizer:
    createHistos: true
    clusterizer: kClusterizerv3
    cellTimeMin: -500e-9
    cellTimeMax: +500e-9
    clusterTimeLength: 1e6
    recalDistToBadChannels: true
    remapMcAod: false
    diffEAggregation: 0.0
    load1DBadChMap: true
Clusterizer_defaultSetting:
    enabled: true
    cellE: 0.1
    seedE: 0.5
Clusterizer_S500A100:
    enabled: true
    cellE: 0.1
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A100
Clusterizer_S500A125:
    enabled: true
    cellE: 0.125
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A125
Clusterizer_S500A150:
    enabled: true
    cellE: 0.15
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A150
Clusterizer_S500A300:
    enabled: true
    cellE: 0.3
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A300
Clusterizer_S1000A300:
    enabled: true
    cellE: 0.3
    seedE: 1.0
    clusterContainersNames:
        - ClusterContainerS1000A300
Clusterizer_V1:
    enabled: true
    clusterizer: kClusterizerv1
    cellE: 0.1
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerV1

ClusterExotics:
    enabled: true
    createHistos: true
    fMaxFcross: 0.97
    fHighEnergyNdiffCut: 50
    fMinCellEnNdiffCut: 0
ClusterExotics_defaultSetting:
    enabled: true
ClusterExotics_V1:
    enabled: true
