configurationName: "PWGJE Sample Configuration"
pass: "pass2"
CellEnergy:
    enabled: false
    createHistos: true	
CellBadChannel:
    enabled: true
    createHistos: true
CellTimeCalib:
    enabled: false
    createHistos: true
Clusterizer:
    enabled: true
    # Note: These are the same values as in the defualt configuration, but these often need to be set and
    #       included here as a reminder.
    clusterizer: kClusterizerv3
    cellE: 0.1
    seedE: 0.3
    cellTimeMin: -1
    cellTimeMax: +1
    clusterTimeLength: 1
    createHistos: true
ClusterExotics:
    enabled: true
    createHistos: true
ClusterNonLinearity:
    enabled: true
    createHistos: true
    nonLinFunct: kPi0MCv3
ClusterTrackMatcher:
    enabled: true
    createHistos: true
ClusterHadronicCorrection:
    enabled: true
    createHistos: true
    doMomDepMatching: true

